# Generated by Django 5.0.7 on 2024-08-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todoitem_todo_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='name',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
